layout_spectrum: 0.4291398871978652
typography_spectrum: 0.0883323046703371
color:
  brandStrength: 0.214900494657254
  lightness: 0.99903010920686
  saturation: 0.22449618944289662
  rhythmicContrast: 0.5095162344174368
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: rebais
content: []
title: Rebais; le meilleur en retour d'argent
description: >-
  C'est extrêmement simple; vous achetez dans votre site web préféré et le site
  "cashback" vous retourne la commission de publicité. Le reBais c'est le moyen
  idéal pour acheter à rabais en ligne. Idéal pour les revendeurs! Recevez de 7
  a 15% en retour sur TOUS vos achats en ligne. Ici je vous donne le meilleur
  des sites a reBais. A vous de choisir...
github: true
favicon: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e72ea541-1334-4eeb-b740-526123d8fd4e.gif
